---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: server01
    driver:
      network:
        - ["private_network", { ip: "172.29.129.181" }]
  - name: server02
    driver:
      network:
        - ["private_network", { ip: "172.29.129.182" }]
  - name: client
    driver:
      network:
        - ["private_network", { ip: "172.29.129.183" }]
